### ISSUE TITLE
Customer

### ISSUE THREAD

**Issue by hooncp** [CS2102-19-20-group56/CS2102#31]
When deliver area is not chosen, no food will be shown
![image](https://user-images.githubusercontent.com/48883554/81050768-29573680-8ef3-11ea-888a-eec8d9d5698e.png)
![image](https://user-images.githubusercontent.com/48883554/81050799-370cbc00-8ef3-11ea-9392-7a2bfafd5a0b.png)

**Comment by jityong** [comment]
this one we just make sure to choose a location when we demo?

**Comment by hooncp** [comment]
Ok!
