### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by hooncp** [CS2102-19-20-group56/CS2102#7]
FDS Manager:

- [ ] Crud 

- [x] For each month, the total number of new customers, the total number of orders, and the total cost of all orders.
- [x] For each for each month and for each customer who has placed some order for that month,
the total number of orders placed by the customer for that month and the total cost of all
these orders.
- [x] For each hour and for each delivery location area, the total number of orders placed at that
hour for that location area.
- [x] For each rider and for each month, the total number of orders delivered by the rider for that
month, the total number of hours worked by the rider for that month, the total salary earned
by the rider for that month, the average delivery time by the rider for that month, the number
of ratings received by the rider for all the orders delivered for that month, and the average
rating received by the rider for all the orders delivered for that month.

**Comment by jityong** [comment]
Rider

- [x] on create rider, choose if monthly or weekly 

- [x] create a schedule (monthly & weekly) -> choose start date, plan schedule for one week

- [x] total number of orders delivered by rider

- [x] total number of hours worked by the rider for that month

- [x] total salary earned by the rider for that month

- [x] average delivery time by the rider for that month

- [x] number of ratings received by rider for all orders delivered for that month

- [x] averaged rating received by rider for orders delivered that month

- [x] Browsing summary info for delivery riders -> weekly/monthly info on
        (a) total num of orders delivered,
	(b) total num of hours worked
	(c) total salary earned

**Comment by eejian97** [comment]
Customer API:

- [x] CRUD for Customer 

- [x] Customer can view past orders
- [x] Customer can view past review posting 
- [x] Customer can browse / search for food 
- [x] Total number of order for that customer and total price of orders, for that month

**Comment by hooncp** [comment]
Restaurant Staff:

- [x] For each month, the total number of completed orders, the total cost of all completed orders
(excluding delivery fees), and the top 5 favorite food items (in terms of the number of orders
for that item).

- [x] For each promotional campaign, the duration (in terms of the number of days/hours) of the
campaign, and the average number of orders received during the promotion (i.e., the ratio of
the total number of orders received during the campaign duration to the number of days/hours
in the campaign duration).

**Comment by hooncp** [comment]
Things to do:

- [x] come up with a decent sized database 10ish entries

**Comment by weidonglim** [comment]
Order
- [x] Create an Order
- [x] Calculate totalprice for each contains
- [x] applies promotion to order
- [ ] able to add food to contains
- [x] use rewardspoint
- [x] give reward point

**Comment by hooncp** [comment]
Trigger function for Orders and Promotions:

- [ ] Every order that has a promotion needs to check for the promotions constrains such as 
the minAmount as well as timelastOrdered

- [ ] Order's attribute of ApplicableTo needs to be the same as Contains attribute of rname

~~Trigger functions for used reward points into Order~~

- [ ]  ~~make sure earned rewardPoints  < total reward Pt
and rewardPoints/5 cannot be greater than finalprice.~~
